### ISSUE TITLE
Trying to load weight data for model of 7 layers

### ISSUE THREAD

**Issue by ncorovic1** [emilwallner/Screenshot-to-code#37]
I've been looking everywhere to find weight data that your model of 7 layers would support. On each of the used ones, I get an error: "You are trying to load a weight file containing 8 layers into a model with 7 layers". I also tried adjusting the model to work with 8 layers, but had no luck with it. 

**It would be of great help if you could provide me a direct link to data that your model would support, or a direct link to code with 8 layer model.**

![image](https://user-images.githubusercontent.com/11291134/53302841-32666580-3863-11e9-9a97-eb67d7ce8e14.png)

**Comment by emilwallner** [comment]
The exact model (model.json) and weights can be found here: https://www.floydhub.com/emilwallner/datasets/imagetocode

You can print the model with model.summary()
