### ISSUE TITLE
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

### ISSUE THREAD

**Issue by nqdy666** [emilwallner/Screenshot-to-code#43]
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

![image](https://user-images.githubusercontent.com/5211893/65676461-8861ec80-e082-11e9-90e1-4cf13435cc2f.png)

**Comment by emilwallner** [comment]
https://stackoverflow.com/questions/54665842/when-importing-tensorflow-i-get-the-following-error-no-module-named-numpy-cor
