### ISSUE TITLE
How to compile and get html for a new image

### ISSUE THREAD

**Issue by sruthisripathi** [emilwallner/Screenshot-to-code#44]
Hi,
I just came across this github repository. I don't have much knowledge in the area. I just wanted to check the model with a couple of images I have. But the readme doesn't provide proper documentation. Can someone please tell me how to generate code for an image using the model provided in [this link](https://www.floydhub.com/emilwallner/datasets/imagetocode/)

**Comment by emilwallner** [comment]
Hi Sruthi, the generator is not included in the project, the dataset comes from https://github.com/tonybeltramelli/pix2code . If you make one, please make a PR.
