### ISSUE TITLE
Shape Incompatible 

### ISSUE THREAD

**Issue by hoangaeye** [emilwallner/Screenshot-to-code#51]
I'm attempting to train the data set for HTML. 

I downloaded the files from: https://www.floydhub.com/emilwallner/datasets/html_models
It failed at the ipython part

```
%%javascript
IPython.OutputArea.prototype._should_scroll = function(lines) {
    return false;
}
```
That was only because I don't have ipython installed. 

I tried taking the last `org-weights-epoch-XXXX---loss-X.XXXX.hdf5`
with the HTML_preloaded_weights.py and got the error below. Am I doing this correctly? 

```
  File "/home/ubuntu/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow_core/python/framework/tensor_shape.py", line 1110, in assert_is_compatible_with
    raise ValueError("Shapes %s and %s are incompatible" % (self, other))
ValueError: Shapes (436, 200) and (441, 200) are incompatible
```

**Comment by emilwallner** [comment]
Please use Floydhub's click-to-run setup in the readme if you are having issues running it locally.
