### ISSUE TITLE
examples

### ISSUE THREAD

**Issue by yishairasowsky** [emilwallner/Screenshot-to-code#52]
@emilwallner 
i am getting a 404 error when i click on these examples
![image](https://user-images.githubusercontent.com/39579959/76780923-861d5700-67b6-11ea-8503-d0a7b1090f69.png)

**Comment by emilwallner** [comment]
I've moved the hosting, they can be found here: https://github.com/emilwallner/emilwallner.github.io/tree/304801b157539ff76eb2ff6e9509e4a7ec1fa8c7/html
