### ISSUE TITLE
love your work

### ISSUE THREAD

**Issue by yishairasowsky** [emilwallner/Screenshot-to-code#53]
@emilwallner 
i love what you have created here!
what did you mean by this:
![image](https://user-images.githubusercontent.com/39579959/78273030-f3e7b380-7516-11ea-8064-f8eeec82bdf2.png)

**Comment by emilwallner** [comment]
Thanks! Start small, and then gradually increase complexity. It's better to start with a toy dataset with a few examples, to understand the dynamics of the problem.  Here is more info on the Geocities dataset: https://www.wired.com/2010/11/geocities-lives-on-as-massive-torrent-download/

**Comment by yishairasowsky** [comment]
@emilwallner
what did you mean that: Picture-to-code networks are image caption models in disguise.

**Comment by emilwallner** [comment]
They have the same type of architecture.
