### ISSUE TITLE
output data jupyter notebook on colab 

### ISSUE THREAD

**Issue by sridhar9999** [emilwallner/Screenshot-to-code#54]
i can run code succesfully in google collab but the problem is it is not showing the output code 
please tell me the output directory

**Comment by sridhar9999** [comment]
please refer this https://colab.research.google.com/github/emilwallner/Screenshot-to-code/blob/master/HTML/HTML.ipynb#scrollTo=DHom1E0wFSFC

the saame problem with the bootstrap one too 
please give me the solution to work this on colab 
sorry for my bad engish

**Comment by sridhar9999** [comment]
And I can't afford flyodhub bro please help me

**Comment by emilwallner** [comment]
I don't have the bandwidth to work this out, but if you fix it, please let me know and I can add it to the readme, so we can help people in a similar situation.
